# https://github.com/docker/build-push-action/blob/master/docs/advanced/tags-labels.md

name: Release docker

on:
    push:
        branches:
            - 'main'

jobs:
    strapi:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Docker meta
                id: meta
                uses: docker/metadata-action@v3
                with:
                    # list of Docker images to use as base name for tags
                    images: |
                        ghcr.io/janmikes/celadna.cz-strapi
                    # generate Docker tags based on the following events/attributes
                    tags: |
                        type=ref,event=branch
                        type=ref,event=pr

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1

            -   name: Cache Docker layers
                uses: actions/cache@v2
                with:
                    path: /tmp/.buildx-cache
                    key: ${{ runner.os }}-buildx-${{ github.sha }}
                    restore-keys: |
                        ${{ runner.os }}-buildx-

            -   name: Login to GHCR
                if: github.event_name != 'pull_request'
                uses: docker/login-action@v1
                with:
                    registry: ghcr.io
                    username: ${{ github.repository_owner }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Build and push Strapi
                uses: docker/build-push-action@v2
                with:
                    context: ./strapi
                    push: ${{ github.event_name != 'pull_request' }}
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}
                    cache-from: type=local,src=/tmp/.buildx-cache
                    cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

            # Temp fix
            # https://github.com/docker/build-push-action/issues/252
            # https://github.com/moby/buildkit/issues/1896
            -   name: Move cache
                run: |
                    rm -rf /tmp/.buildx-cache
                    mv /tmp/.buildx-cache-new /tmp/.buildx-cache

    frontend:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Docker meta
                id: meta
                uses: docker/metadata-action@v3
                with:
                    # list of Docker images to use as base name for tags
                    images: |
                        ghcr.io/janmikes/celadna.cz-frontend
                    # generate Docker tags based on the following events/attributes
                    tags: |
                        type=ref,event=branch
                        type=ref,event=pr

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1

            -   name: Cache Docker layers
                uses: actions/cache@v2
                with:
                    path: /tmp/.buildx-cache
                    key: ${{ runner.os }}-buildx-${{ github.sha }}
                    restore-keys: |
                        ${{ runner.os }}-buildx-

            -   name: Login to GHCR
                if: github.event_name != 'pull_request'
                uses: docker/login-action@v1
                with:
                    registry: ghcr.io
                    username: ${{ github.repository_owner }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Build and push Frontend
                uses: docker/build-push-action@v2
                with:
                    context: ./frontend
                    push: ${{ github.event_name != 'pull_request' }}
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}
                    cache-from: type=local,src=/tmp/.buildx-cache
                    cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

            # Temp fix
            # https://github.com/docker/build-push-action/issues/252
            # https://github.com/moby/buildkit/issues/1896
            -   name: Move cache
                run: |
                    rm -rf /tmp/.buildx-cache
                    mv /tmp/.buildx-cache-new /tmp/.buildx-cache
