# https://github.com/docker/build-push-action/blob/master/docs/advanced/tags-labels.md

name: Strapi

on:
    push:
        branches:
            - 'main'
        paths:
            - 'strapi/**'

jobs:
    docker-image:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Docker meta
                id: meta
                uses: docker/metadata-action@v3
                with:
                    # list of Docker images to use as base name for tags
                    images: |
                        ghcr.io/janmikes/celadna.cz-strapi
                    # generate Docker tags based on the following events/attributes
                    tags: |
                        type=ref,event=branch
                        type=ref,event=pr

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1

            -   name: Cache Docker layers
                uses: actions/cache@v2
                with:
                    path: /tmp/.buildx-cache
                    key: ${{ runner.os }}-buildx-${{ github.sha }}
                    restore-keys: |
                        ${{ runner.os }}-buildx-

            -   name: Login to GHCR
                if: github.event_name != 'pull_request'
                uses: docker/login-action@v1
                with:
                    registry: ghcr.io
                    username: ${{ github.repository_owner }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Build and push Strapi
                uses: docker/build-push-action@v2
                with:
                    context: ./strapi
                    push: ${{ github.event_name != 'pull_request' }}
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}
                    cache-from: type=local,src=/tmp/.buildx-cache
                    cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

            # Temp fix
            # https://github.com/docker/build-push-action/issues/252
            # https://github.com/moby/buildkit/issues/1896
            -   name: Move cache
                run: |
                    rm -rf /tmp/.buildx-cache
                    mv /tmp/.buildx-cache-new /tmp/.buildx-cache

    deploy:
        needs:
            - docker-image
        steps:
            - name: executing remote ssh commands using ssh key
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.DEPLOY_HOST }}
                username: ${{ secrets.DEPLOY_USERNAME }}
                key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
                port: ${{ secrets.DEPLOY_PORT }}
                script_stop: true
                script: |
                  cd /app
                  docker-compose pull strapi
                  docker-compose up -d strapi
